framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
        channel_policy:
            urgent: ['chat/slack']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
